#!/usr/bin/env node

let fs = require("fs");
let Phrase = require("mhartl-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
for (let line of text.split("\n")) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
        console.log("palindrome detected:", line);
        fs.appendFileSync("palindrome.txt", line + "\n");
    }
}